Adapt tests to sbt-release 1.4.0
sbt-release 1.4.0 introduced a breaking change, causing the following
error in tests:

```
java.lang.RuntimeException: Expected snapshot version. Received: 0.0.1
```

More details here:
https://github.com/sbt/sbt-release/releases/tag/v1.4.0

This commit restores the old behavior.